# Generated by Django 2.1.1 on 2018-09-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness_Basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtitletitle',
            new_name='subtitle',
        ),
    ]
