# Generated by Django 2.1.1 on 2018-09-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness_Basic', '0002_auto_20180911_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
