# Generated by Django 2.1.1 on 2018-09-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness_Basic', '0006_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
