# Generated by Django 2.1.1 on 2018-09-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness_Basic', '0010_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
