# Generated by Django 2.1.1 on 2018-09-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness_Basic', '0011_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
