# Generated by Django 2.1.1 on 2018-09-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Fat', models.CharField(max_length=100)),
                ('Carb', models.CharField(max_length=100)),
                ('Protein', models.CharField(max_length=100)),
                ('Fibre', models.CharField(max_length=100)),
                ('NetCarb', models.CharField(max_length=100)),
                ('Calorie', models.CharField(max_length=100)),
            ],
        ),
    ]
